import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'Midnight Velvet Blazer',
    description: 'A luxurious velvet blazer in deep midnight blue, perfect for formal evenings. Tailored fit with satin lapels.',
    price: 12500,
    category: 'Men',
    images: ['https://images.unsplash.com/photo-1594932224828-b4b057b7d6ee?q=80&w=800&auto=format&fit=crop'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Midnight Blue', 'Black'],
    stock: 15,
    isNewArrival: true,
    isSale: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p2',
    name: 'Silk Ethereal Gown',
    description: 'Breathtaking silk gown with hand-embroidered details. Flowing silhouette with a delicate waist belt.',
    price: 24000,
    category: 'Women',
    images: ['https://images.unsplash.com/photo-1539008835279-4346809ec014?q=80&w=800&auto=format&fit=crop'],
    sizes: ['XS', 'S', 'M', 'L'],
    colors: ['Cream', 'Soft Rose'],
    stock: 8,
    isNewArrival: true,
    isSale: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p3',
    name: 'Urban Tech Trench',
    description: 'Weather-resistant trench coat with contemporary urban design. Hidden pockets and adjustable cuffs.',
    price: 9500,
    category: 'Men',
    images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=800&auto=format&fit=crop'],
    sizes: ['M', 'L', 'XL'],
    colors: ['Desert Tan', 'Slate Grey'],
    stock: 20,
    isNewArrival: false,
    isSale: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p4',
    name: 'Heritage Wool Sweater',
    description: 'Fine merino wool sweater with heritage knit pattern. Exceptionally warm yet breathable.',
    price: 6800,
    category: 'Men',
    images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?q=80&w=800&auto=format&fit=crop'],
    sizes: ['S', 'M', 'L'],
    colors: ['Forest Green', 'Navy'],
    stock: 30,
    isNewArrival: false,
    isSale: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p5',
    name: 'Aurelia Gold Clutch',
    description: 'Evening clutch with gold-tone hardware and structured frame. Comes with a detachable chain strap.',
    price: 4500,
    category: 'Accessories',
    images: ['https://images.unsplash.com/photo-1566150905458-1bf1fd143c86?q=80&w=800&auto=format&fit=crop'],
    sizes: ['One Size'],
    colors: ['Gold', 'Silver'],
    stock: 12,
    isNewArrival: true,
    isSale: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'p6',
    name: 'Linen Breezeway Dress',
    description: 'Lightweight linen dress perfect for summer afternoons. Relaxed fit with wooden button details.',
    price: 7200,
    category: 'Women',
    images: ['https://images.unsplash.com/photo-1496747611176-843222e1e57c?q=80&w=800&auto=format&fit=crop'],
    sizes: ['S', 'M', 'L'],
    colors: ['Sage', 'Oatmeal'],
    stock: 25,
    isNewArrival: false,
    isSale: true,
    createdAt: new Date().toISOString(),
  }
];
